- name: Dynamic Inventory Setup
  block:
    - name: Read hosts file into a variable
      ansible.builtin.shell:
        cmd: cat hosts.txt
      register: host_file_content
      changed_when: false

    - name: Create array of hosts from file content
      ansible.builtin.set_fact:
        hosts_list: '{{ host_file_content.stdout_lines }}'
      changed_when: false

    - name: Add host dynamically
      ansible.builtin.add_host:
        name: '{{ item }}'
        ansible_host: '{{ item }}'
        ansible_user: '{{ dynamic_inventory_ansible_user }}'
        ansible_ssh_private_key_file: '{{ ansible_ssh_private_key_file }}'
        groups: ec2_instances
      with_items: '{{ hosts_list }}'
  rescue:
    - name: Fail job and display error message
      ansible.builtin.fail:
        msg: 'Dynamic inventory creation failed'
