- name: Docker installation process started
  become: true
  block:
    - name: Update all packages to the latest version
      ansible.builtin.yum:
        name: '*'

    - name: Install Docker
      ansible.builtin.yum:
        name: docker
        state: present
        update_cache: true

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to the docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: true

    - name: Create target directory
      ansible.builtin.file:
        path: '{{ setup_docker_target_dir }}'
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Transfer the .env file to the EC2 instance
      ansible.builtin.copy:
        src: '{{ setup_docker_env_file_source }}'
        dest: '{{ setup_docker_env_file_destination }}'
        owner: ec2-user
        group: ec2-user
        mode: '0644'

  rescue:
    - name: Fail job and display error message
      ansible.builtin.fail:
        msg: 'Docker Setup failed on {{ ansible_hostname }}'
