- name: Initial Inventory Setup
  hosts: localhost
  tasks:
    - name: Setup Docker on the host machines
      ansible.builtin.import_role:
        name: dynamic_inventory

- name: Setting up Docker and configuring ECR on host machines
  hosts: ec2_instances
  tasks:
    - name: Setup Docker on the host machines
      ansible.builtin.import_role:
        name: setup_docker

    - name: Setup ECR on the host machines
      ansible.builtin.import_role:
        name: aws_ecr

    - name: Signal that the automation is completed
      ansible.builtin.debug:
        msg: 'AUTOMATION HAS BEEN COMPLETED.'
